version: "3.9"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: /bin/bash -c "while sleep 1000; do :; done"
    depends_on:
      - grobid

  grobid:
    image: grobid/grobid:0.8.2-crf
    restart: unless-stopped
    ports:
      - "8070:8070"
      - "8071:8071"
