version: "3.8"
services:
  workspace:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    depends_on:
      - grobid
    tty: true

  grobid:
    image: grobid/grobid:0.8.2-crf
    # if Codespaces runs on ARM, force amd64 emulation (may be slower). Remove platform if using x86.
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8070:8070"   # API
      - "8071:8071"   # admin/health console
    environment:
      JAVA_OPTS: "-Xms512m -Xmx2g"
    # Optional: increase ulimits if you ever hit PDF processing memory issues
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
